spring:
  application:
    name: cocktail-bot
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/cocktail_bot?createIfNotExists=true
    username: root
    password: root
  main:
    allow-circular-references: true
